### ISSUE TITLE
Im getting control characters on line

### ISSUE THREAD

**Issue by hackervera** [cldwalker/tux#2]
if i hit 'up' i get '^[[A' on the output, using ripl this doesn't happen. I'm running tux as 'bundle exec tux' not sure if that might have anything to do with it. This is happening on ubuntu server, on macosx localhost there is no control character issue

**Comment by cldwalker** [comment]
Are you seeing this issue with irb on this server?

**Comment by hackervera** [comment]
Nope, irb and ripl work fine, its just tux

**Comment by cldwalker** [comment]
Reporting Readline version, ruby version and OS version for starters would help. But to really fix this I need a way to reproduce it. This means a bare failing environment which means a Gemfile an AMI and if possible a chef recipe for the server.

**Comment by cldwalker** [comment]
Closing. I can reopen if you give the above information.
