### ISSUE TITLE
Feature request: Ability to reload the app within a tux session

### ISSUE THREAD

**Issue by clizzin** [cldwalker/tux#3]
My app is set up such that the main file is app.rb, and that file requires several files that contain models.  If I update one of these models, I have to kill my tux session and then start another tux session in order to force a reload.  I would like if I could call "reload!" within the tux session, similar to the Rails console.  It might also be helpful in some cases of highly iterative development if I could set a command-line flag at session start time to always reload the session.

If this feature already exists in some form, then this issue would be solved by a clearer description of that feature in the README.  Thanks!

**Comment by cldwalker** [comment]
You can drop this in your irbrc or in your sinatra app:

``` ruby
def reload!
  exec $0, *ARGV
end
```

This will just literally replace your current tux session with a new one. Always reloading is a more complex issue and requires dipping into ruby's autoloading functionality. Patches welcome for that ;)

**Comment by cldwalker** [comment]
Closing as I assume silence means this is good enough. If you have more to discuss I can reopen.

**Comment by clizzin** [comment]
Putting that in my `~/.irbrc` worked great.  Thank you!

**Comment by johnnygoodman** [comment]
Same here. Thanks for the instructions. Would you accept a pull request that updates the docs to mention this feature? I suspect a lot of people love tux but don't know this is available.

**Comment by cldwalker** [comment]
@johnnygoodman Sure. It's not a feature of tux but an orthogonal tip. Feel free to add it to a section called Tips after Usage.

**Comment by bwiggs** [comment]
@cldwalker Thanks for that snippet, super helpful!
