### ISSUE TITLE
tux has trouble loading gems sourced from git repositories

### ISSUE THREAD

**Issue by clizzin** [cldwalker/tux#4]
My `Gemfile` has a gem that is loaded via a git source:

```
gem 'zendesk-api', :git => 'git@github.com:clizzin/zendesk-api.git', :ref => '19f8dc4dd772891bd353f63c093b956e2ab2ad6e'
```

tux has trouble loading this gem because of a load path issue.  This seems like a bug rather than just the way gems are supposed to work because other tools like shotgun/WEBrick have no trouble loading the gem correctly.  I'll try to debug this on my own and submit a patch if I can figure it out, but I wanted to note it here too in case more experienced minds have any ideas.

The `models.rb` file has a line:

```
require 'zendesk-api'
```

This triggers the following stacktrace (note that some of the lines are there because I'm also using ActiveRecord/ActiveSupport in my project, but I'm pretty sure that part is irrelevant to whether or not the load path can locate a git gem);

```
/Users/clizzin/.rvm/gems/ruby-1.8.7-p352@myproject/gems/ripl-rack-0.2.0/lib/ripl/rack.rb:38:in `initialize': /Users/clizzin/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require': no such file to load -- zendesk-api (LoadError)
    from /Users/clizzin/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from /Users/clizzin/.rvm/gems/ruby-1.8.7-p352@myproject/gems/activesupport-3.0.10/lib/active_support/dependencies.rb:239:in `require'
    from /Users/clizzin/.rvm/gems/ruby-1.8.7-p352@myproject/gems/activesupport-3.0.10/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /Users/clizzin/.rvm/gems/ruby-1.8.7-p352@myproject/gems/activesupport-3.0.10/lib/active_support/dependencies.rb:593:in `new_constants_in'
    from /Users/clizzin/.rvm/gems/ruby-1.8.7-p352@myproject/gems/activesupport-3.0.10/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /Users/clizzin/.rvm/gems/ruby-1.8.7-p352@myproject/gems/activesupport-3.0.10/lib/active_support/dependencies.rb:239:in `require'
    from ./models.rb:4
    from /Users/clizzin/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Users/clizzin/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from ./app.rb:2
    from /Users/clizzin/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Users/clizzin/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from (eval):1:in `initialize'
    from /Users/clizzin/.rvm/gems/ruby-1.8.7-p352@myproject/gems/rack-1.4.1/lib/rack/builder.rb:51:in `instance_eval'
    from /Users/clizzin/.rvm/gems/ruby-1.8.7-p352@myproject/gems/rack-1.4.1/lib/rack/builder.rb:51:in `initialize'
    from (eval):1:in `new'
    from (eval):1:in `initialize'
    from /Users/clizzin/.rvm/gems/ruby-1.8.7-p352@myproject/gems/ripl-rack-0.2.0/lib/ripl/rack.rb:18:in `eval'
    from /Users/clizzin/.rvm/gems/ruby-1.8.7-p352@myproject/gems/ripl-rack-0.2.0/lib/ripl/rack.rb:38:in `initialize'
    from /Users/clizzin/.rvm/gems/ruby-1.8.7-p352@myproject/gems/ripl-rack-0.2.0/lib/ripl/rack.rb:18:in `new'
    from /Users/clizzin/.rvm/gems/ruby-1.8.7-p352@myproject/gems/ripl-rack-0.2.0/lib/ripl/rack.rb:18:in `rack'
    from /Users/clizzin/.rvm/gems/ruby-1.8.7-p352@myproject/gems/ripl-rack-0.2.0/lib/ripl/rack.rb:9:in `before_loop'
    from /Users/clizzin/.rvm/gems/ruby-1.8.7-p352@myproject/gems/ripl-multi_line-0.3.0/lib/ripl/multi_line.rb:19:in `before_loop'
    from /Users/clizzin/.rvm/gems/ruby-1.8.7-p352@myproject/gems/ripl-0.6.3/lib/ripl/readline.rb:6:in `before_loop'
    from /Users/clizzin/.rvm/gems/ruby-1.8.7-p352@myproject/gems/ripl-0.6.3/lib/ripl/completion.rb:5:in `before_loop'
    from /Users/clizzin/.rvm/gems/ruby-1.8.7-p352@myproject/gems/ripl-0.6.3/lib/ripl/shell.rb:29:in `loop'
    from /Users/clizzin/.rvm/gems/ruby-1.8.7-p352@myproject/gems/ripl-0.6.3/lib/ripl/runner.rb:49:in `start'
    from /Users/clizzin/.rvm/gems/ruby-1.8.7-p352@myproject/gems/ripl-0.6.3/lib/ripl/runner.rb:31:in `run'
    from /Users/clizzin/.rvm/gems/ruby-1.8.7-p352@myproject/gems/tux-0.3.0/bin/tux:7
    from /Users/clizzin/.rvm/gems/ruby-1.8.7-p352@myproject/bin/tux:23:in `load'
    from /Users/clizzin/.rvm/gems/ruby-1.8.7-p352@myproject/bin/tux:23
```

**Comment by cldwalker** [comment]
tux doesn't touch $LOAD_PATH and lets rubygems handle that. It sounds like you have a bundler/rubygems setup issue. Judging from your stack trace it seems the require is failing in config.ru. Why? If you drop your Gemfile and config.ru, I'll take a look.

**Comment by cldwalker** [comment]
Closing. I can reopen if you give the above information.

**Comment by mhaseebkhan** [comment]
I'm getting this issue, Can you please help

shahid@shahid-ubuntu:~/html5-project/Beaver$ rails s
/home/shahid/.rvm/gems/ree-1.8.7-2011.03@global/gems/bundler-1.2.1/lib/bundler/runtime.rb:74:in `require': no such file to load -- zendesk/api (LoadError)
    from /home/shahid/.rvm/gems/ree-1.8.7-2011.03@global/gems/bundler-1.2.1/lib/bundler/runtime.rb:74:in`require'
    from /home/shahid/.rvm/gems/ree-1.8.7-2011.03@global/gems/bundler-1.2.1/lib/bundler/runtime.rb:55:in `each'
    from /home/shahid/.rvm/gems/ree-1.8.7-2011.03@global/gems/bundler-1.2.1/lib/bundler/runtime.rb:55:in`require'
    from /home/shahid/.rvm/gems/ree-1.8.7-2011.03@global/gems/bundler-1.2.1/lib/bundler.rb:128:in `require'
    from /home/shahid/html5-project/Beaver/config/application.rb:16
    from /home/shahid/.rvm/gems/ree-1.8.7-2011.03@v3/gems/railties-3.0.12/lib/rails/commands.rb:28:in`require'
    from /home/shahid/.rvm/gems/ree-1.8.7-2011.03@v3/gems/railties-3.0.12/lib/rails/commands.rb:28
    from /home/shahid/.rvm/gems/ree-1.8.7-2011.03@v3/gems/railties-3.0.12/lib/rails/commands.rb:27:in `tap'
    from /home/shahid/.rvm/gems/ree-1.8.7-2011.03@v3/gems/railties-3.0.12/lib/rails/commands.rb:27
    from script/rails:6:in`require'
    from script/rails:6
