### ISSUE TITLE
tux and logging problem

### ISSUE THREAD

**Issue by sjoonk** [cldwalker/tux#5]
When I use this logging redirection code within my config.ru file,

  log = File.new("log/sinatra.log", "a+")
  STDOUT.reopen(log)
  STDERR.reopen(log)

then, tux seems not working.. just silent without promit..

Is there any way to prevent this problem??

**Comment by cldwalker** [comment]
You can try STDOUT.flush and STDERR.flush after reopening. If that doesn't work then I recommend not reopening since that is causing this problem.

**Comment by cldwalker** [comment]
Closing. Feel free to respond and I can reopen.
