### ISSUE TITLE
irbrc confusions - undefined method `conf' for IRB:Module

### ISSUE THREAD

**Issue by timwaters** [cldwalker/tux#6]
When loading tux I get a 

undefined method `conf' for IRB:Module

Error.

I have followed the advice here: https://github.com/cldwalker/ripl#coming-from-irb

and have tried both the 
if defined? IRB workaround and installing the suggested gem, however I still get the same kind of error:

ripl: Error while loading ~/.irbrc:
NoMethodError: undefined method `conf' for IRB:Module

To workaround this, I have used:

```
if defined IRB.conf
  IRB.conf[:blah]...

```

**Comment by cldwalker** [comment]
Thanks for reporting your issue! This is [one of my 12 active issues](https://gh-active-issues.herokuapp.com/#cldwalker/tux#6). Use that link to check how soon your issue will be answered. Don't forget to check your issue against this project's CONTRIBUTING.md. Cheers.

**Comment by cldwalker** [comment]
Hmm. Did you add `require 'ripl/irb'` to ~/.irbrc before `IRB` as stated in the [readme](https://github.com/cldwalker/ripl-irb#usage)?

If you did and it's still an issue, I'll need versions of ripl, tux, your output of `gem env` and your failing ~/.irbrc

**Comment by timwaters** [comment]
The readme says ~/.riplrc . I added require 'ripl/irb'  to  both my .irbrc and a new .riplrc file, and tried both respectively.
I think it's because I am using RVM and a gemset with tux and ripl -  but the tux and ripl gems are not installed globally and so that doesn't work - seems fair enough. I'm not sure if it would be expected to work though?

I'm happy with the IRB.conf workaround for the meantime.

**Comment by cldwalker** [comment]
Gah. I meant riplrc. I don't think rvm is the culprit here. However, since this workaround works for you I'll close. I can reopen if you want to solve the cause, but I would need what I stated above as well as your ~/.riplrc

**Comment by vigo** [comment]
in your `.irbrc` file; wrap all of your content:

```
if IRB.singleton_methods.include?(:conf)
  IRB.conf[:USE_READLINE] = true
  IRB.conf[:AUTO_INDENT] = true
 # other stuff...
end
```
